export default {
  login: 'shadmanAh',
  id: 37769662,
  node_id: 'MDQ6VXNlcjM3NzY5NjYy',
  avatar_url: 'https://avatars.githubusercontent.com/u/37769662?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/shadmanAh',
  html_url: 'https://github.com/shadmanAh',
  followers_url: 'https://api.github.com/users/shadmanAh/followers',
  following_url:
    'https://api.github.com/users/shadmanAh/following{/other_user}',
  gists_url: 'https://api.github.com/users/shadmanAh/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/shadmanAh/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/shadmanAh/subscriptions',
  organizations_url: 'https://api.github.com/users/shadmanAh/orgs',
  repos_url: 'https://api.github.com/users/shadmanAh/repos',
  events_url: 'https://api.github.com/users/shadmanAh/events{/privacy}',
  received_events_url: 'https://api.github.com/users/shadmanAh/received_events',
  type: 'User',
  site_admin: false,
  name: 'Shadman',
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: 'BS - Software Engineering\r\nMS - Artificial Intelligence',
  twitter_username: null,
  public_repos: 37,
  public_gists: 0,
  followers: 1,
  following: 4,
  created_at: '2018-03-25T09:12:34Z',
  updated_at: '2023-08-07T13:07:26Z',
}
